// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
namespace mq {
class BasicProperties;
class BasicPropertiesDefaultTypeInternal;
extern BasicPropertiesDefaultTypeInternal _BasicProperties_default_instance_;
class Message;
class MessageDefaultTypeInternal;
extern MessageDefaultTypeInternal _Message_default_instance_;
class Message_Payload;
class Message_PayloadDefaultTypeInternal;
extern Message_PayloadDefaultTypeInternal _Message_Payload_default_instance_;
}  // namespace mq
PROTOBUF_NAMESPACE_OPEN
template<> ::mq::BasicProperties* Arena::CreateMaybeMessage<::mq::BasicProperties>(Arena*);
template<> ::mq::Message* Arena::CreateMaybeMessage<::mq::Message>(Arena*);
template<> ::mq::Message_Payload* Arena::CreateMaybeMessage<::mq::Message_Payload>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mq {

enum ExchangeType : int {
  UNKNOWNTYPE = 0,
  DIRECT = 1,
  FANOUT = 2,
  TOPIC = 3,
  ExchangeType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ExchangeType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ExchangeType_IsValid(int value);
constexpr ExchangeType ExchangeType_MIN = UNKNOWNTYPE;
constexpr ExchangeType ExchangeType_MAX = TOPIC;
constexpr int ExchangeType_ARRAYSIZE = ExchangeType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ExchangeType_descriptor();
template<typename T>
inline const std::string& ExchangeType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ExchangeType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ExchangeType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ExchangeType_descriptor(), enum_t_value);
}
inline bool ExchangeType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ExchangeType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ExchangeType>(
    ExchangeType_descriptor(), name, value);
}
enum DeliveryMode : int {
  UNKNOWNMODE = 0,
  UNDURABLE = 1,
  DURABLE = 2,
  DeliveryMode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  DeliveryMode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool DeliveryMode_IsValid(int value);
constexpr DeliveryMode DeliveryMode_MIN = UNKNOWNMODE;
constexpr DeliveryMode DeliveryMode_MAX = DURABLE;
constexpr int DeliveryMode_ARRAYSIZE = DeliveryMode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* DeliveryMode_descriptor();
template<typename T>
inline const std::string& DeliveryMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, DeliveryMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function DeliveryMode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    DeliveryMode_descriptor(), enum_t_value);
}
inline bool DeliveryMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, DeliveryMode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<DeliveryMode>(
    DeliveryMode_descriptor(), name, value);
}
// ===================================================================

class BasicProperties PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mq.BasicProperties) */ {
 public:
  inline BasicProperties() : BasicProperties(nullptr) {}
  virtual ~BasicProperties();

  BasicProperties(const BasicProperties& from);
  BasicProperties(BasicProperties&& from) noexcept
    : BasicProperties() {
    *this = ::std::move(from);
  }

  inline BasicProperties& operator=(const BasicProperties& from) {
    CopyFrom(from);
    return *this;
  }
  inline BasicProperties& operator=(BasicProperties&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const BasicProperties& default_instance();

  static inline const BasicProperties* internal_default_instance() {
    return reinterpret_cast<const BasicProperties*>(
               &_BasicProperties_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BasicProperties& a, BasicProperties& b) {
    a.Swap(&b);
  }
  inline void Swap(BasicProperties* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BasicProperties* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline BasicProperties* New() const final {
    return CreateMaybeMessage<BasicProperties>(nullptr);
  }

  BasicProperties* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<BasicProperties>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const BasicProperties& from);
  void MergeFrom(const BasicProperties& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BasicProperties* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mq.BasicProperties";
  }
  protected:
  explicit BasicProperties(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kRoutingKeyFieldNumber = 3,
    kDeliveryModeFieldNumber = 2,
  };
  // string id = 1;
  void clear_id();
  const std::string& id() const;
  void set_id(const std::string& value);
  void set_id(std::string&& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  std::string* mutable_id();
  std::string* release_id();
  void set_allocated_id(std::string* id);
  private:
  const std::string& _internal_id() const;
  void _internal_set_id(const std::string& value);
  std::string* _internal_mutable_id();
  public:

  // string routing_key = 3;
  void clear_routing_key();
  const std::string& routing_key() const;
  void set_routing_key(const std::string& value);
  void set_routing_key(std::string&& value);
  void set_routing_key(const char* value);
  void set_routing_key(const char* value, size_t size);
  std::string* mutable_routing_key();
  std::string* release_routing_key();
  void set_allocated_routing_key(std::string* routing_key);
  private:
  const std::string& _internal_routing_key() const;
  void _internal_set_routing_key(const std::string& value);
  std::string* _internal_mutable_routing_key();
  public:

  // .mq.DeliveryMode delivery_mode = 2;
  void clear_delivery_mode();
  ::mq::DeliveryMode delivery_mode() const;
  void set_delivery_mode(::mq::DeliveryMode value);
  private:
  ::mq::DeliveryMode _internal_delivery_mode() const;
  void _internal_set_delivery_mode(::mq::DeliveryMode value);
  public:

  // @@protoc_insertion_point(class_scope:mq.BasicProperties)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr routing_key_;
  int delivery_mode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class Message_Payload PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mq.Message.Payload) */ {
 public:
  inline Message_Payload() : Message_Payload(nullptr) {}
  virtual ~Message_Payload();

  Message_Payload(const Message_Payload& from);
  Message_Payload(Message_Payload&& from) noexcept
    : Message_Payload() {
    *this = ::std::move(from);
  }

  inline Message_Payload& operator=(const Message_Payload& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message_Payload& operator=(Message_Payload&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message_Payload& default_instance();

  static inline const Message_Payload* internal_default_instance() {
    return reinterpret_cast<const Message_Payload*>(
               &_Message_Payload_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Message_Payload& a, Message_Payload& b) {
    a.Swap(&b);
  }
  inline void Swap(Message_Payload* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message_Payload* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message_Payload* New() const final {
    return CreateMaybeMessage<Message_Payload>(nullptr);
  }

  Message_Payload* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message_Payload>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message_Payload& from);
  void MergeFrom(const Message_Payload& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message_Payload* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mq.Message.Payload";
  }
  protected:
  explicit Message_Payload(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBodyFieldNumber = 2,
    kVaildFieldNumber = 3,
    kPropertiesFieldNumber = 1,
  };
  // string body = 2;
  void clear_body();
  const std::string& body() const;
  void set_body(const std::string& value);
  void set_body(std::string&& value);
  void set_body(const char* value);
  void set_body(const char* value, size_t size);
  std::string* mutable_body();
  std::string* release_body();
  void set_allocated_body(std::string* body);
  private:
  const std::string& _internal_body() const;
  void _internal_set_body(const std::string& value);
  std::string* _internal_mutable_body();
  public:

  // string vaild = 3;
  void clear_vaild();
  const std::string& vaild() const;
  void set_vaild(const std::string& value);
  void set_vaild(std::string&& value);
  void set_vaild(const char* value);
  void set_vaild(const char* value, size_t size);
  std::string* mutable_vaild();
  std::string* release_vaild();
  void set_allocated_vaild(std::string* vaild);
  private:
  const std::string& _internal_vaild() const;
  void _internal_set_vaild(const std::string& value);
  std::string* _internal_mutable_vaild();
  public:

  // .mq.BasicProperties properties = 1;
  bool has_properties() const;
  private:
  bool _internal_has_properties() const;
  public:
  void clear_properties();
  const ::mq::BasicProperties& properties() const;
  ::mq::BasicProperties* release_properties();
  ::mq::BasicProperties* mutable_properties();
  void set_allocated_properties(::mq::BasicProperties* properties);
  private:
  const ::mq::BasicProperties& _internal_properties() const;
  ::mq::BasicProperties* _internal_mutable_properties();
  public:
  void unsafe_arena_set_allocated_properties(
      ::mq::BasicProperties* properties);
  ::mq::BasicProperties* unsafe_arena_release_properties();

  // @@protoc_insertion_point(class_scope:mq.Message.Payload)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr body_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr vaild_;
  ::mq::BasicProperties* properties_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class Message PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mq.Message) */ {
 public:
  inline Message() : Message(nullptr) {}
  virtual ~Message();

  Message(const Message& from);
  Message(Message&& from) noexcept
    : Message() {
    *this = ::std::move(from);
  }

  inline Message& operator=(const Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline Message& operator=(Message&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Message& default_instance();

  static inline const Message* internal_default_instance() {
    return reinterpret_cast<const Message*>(
               &_Message_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Message& a, Message& b) {
    a.Swap(&b);
  }
  inline void Swap(Message* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Message* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Message* New() const final {
    return CreateMaybeMessage<Message>(nullptr);
  }

  Message* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Message>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Message& from);
  void MergeFrom(const Message& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Message* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mq.Message";
  }
  protected:
  explicit Message(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_msg_2eproto);
    return ::descriptor_table_msg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Message_Payload Payload;

  // accessors -------------------------------------------------------

  enum : int {
    kPayloadFieldNumber = 1,
    kOffsetFieldNumber = 2,
    kLengthFieldNumber = 3,
  };
  // .mq.Message.Payload payload = 1;
  bool has_payload() const;
  private:
  bool _internal_has_payload() const;
  public:
  void clear_payload();
  const ::mq::Message_Payload& payload() const;
  ::mq::Message_Payload* release_payload();
  ::mq::Message_Payload* mutable_payload();
  void set_allocated_payload(::mq::Message_Payload* payload);
  private:
  const ::mq::Message_Payload& _internal_payload() const;
  ::mq::Message_Payload* _internal_mutable_payload();
  public:
  void unsafe_arena_set_allocated_payload(
      ::mq::Message_Payload* payload);
  ::mq::Message_Payload* unsafe_arena_release_payload();

  // uint32 offset = 2;
  void clear_offset();
  ::PROTOBUF_NAMESPACE_ID::uint32 offset() const;
  void set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_offset() const;
  void _internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 length = 3;
  void clear_length();
  ::PROTOBUF_NAMESPACE_ID::uint32 length() const;
  void set_length(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_length() const;
  void _internal_set_length(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:mq.Message)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::mq::Message_Payload* payload_;
  ::PROTOBUF_NAMESPACE_ID::uint32 offset_;
  ::PROTOBUF_NAMESPACE_ID::uint32 length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BasicProperties

// string id = 1;
inline void BasicProperties::clear_id() {
  id_.ClearToEmpty();
}
inline const std::string& BasicProperties::id() const {
  // @@protoc_insertion_point(field_get:mq.BasicProperties.id)
  return _internal_id();
}
inline void BasicProperties::set_id(const std::string& value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:mq.BasicProperties.id)
}
inline std::string* BasicProperties::mutable_id() {
  // @@protoc_insertion_point(field_mutable:mq.BasicProperties.id)
  return _internal_mutable_id();
}
inline const std::string& BasicProperties::_internal_id() const {
  return id_.Get();
}
inline void BasicProperties::_internal_set_id(const std::string& value) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BasicProperties::set_id(std::string&& value) {
  
  id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:mq.BasicProperties.id)
}
inline void BasicProperties::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:mq.BasicProperties.id)
}
inline void BasicProperties::set_id(const char* value,
    size_t size) {
  
  id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:mq.BasicProperties.id)
}
inline std::string* BasicProperties::_internal_mutable_id() {
  
  return id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BasicProperties::release_id() {
  // @@protoc_insertion_point(field_release:mq.BasicProperties.id)
  return id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BasicProperties::set_allocated_id(std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:mq.BasicProperties.id)
}

// .mq.DeliveryMode delivery_mode = 2;
inline void BasicProperties::clear_delivery_mode() {
  delivery_mode_ = 0;
}
inline ::mq::DeliveryMode BasicProperties::_internal_delivery_mode() const {
  return static_cast< ::mq::DeliveryMode >(delivery_mode_);
}
inline ::mq::DeliveryMode BasicProperties::delivery_mode() const {
  // @@protoc_insertion_point(field_get:mq.BasicProperties.delivery_mode)
  return _internal_delivery_mode();
}
inline void BasicProperties::_internal_set_delivery_mode(::mq::DeliveryMode value) {
  
  delivery_mode_ = value;
}
inline void BasicProperties::set_delivery_mode(::mq::DeliveryMode value) {
  _internal_set_delivery_mode(value);
  // @@protoc_insertion_point(field_set:mq.BasicProperties.delivery_mode)
}

// string routing_key = 3;
inline void BasicProperties::clear_routing_key() {
  routing_key_.ClearToEmpty();
}
inline const std::string& BasicProperties::routing_key() const {
  // @@protoc_insertion_point(field_get:mq.BasicProperties.routing_key)
  return _internal_routing_key();
}
inline void BasicProperties::set_routing_key(const std::string& value) {
  _internal_set_routing_key(value);
  // @@protoc_insertion_point(field_set:mq.BasicProperties.routing_key)
}
inline std::string* BasicProperties::mutable_routing_key() {
  // @@protoc_insertion_point(field_mutable:mq.BasicProperties.routing_key)
  return _internal_mutable_routing_key();
}
inline const std::string& BasicProperties::_internal_routing_key() const {
  return routing_key_.Get();
}
inline void BasicProperties::_internal_set_routing_key(const std::string& value) {
  
  routing_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void BasicProperties::set_routing_key(std::string&& value) {
  
  routing_key_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:mq.BasicProperties.routing_key)
}
inline void BasicProperties::set_routing_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  routing_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:mq.BasicProperties.routing_key)
}
inline void BasicProperties::set_routing_key(const char* value,
    size_t size) {
  
  routing_key_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:mq.BasicProperties.routing_key)
}
inline std::string* BasicProperties::_internal_mutable_routing_key() {
  
  return routing_key_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* BasicProperties::release_routing_key() {
  // @@protoc_insertion_point(field_release:mq.BasicProperties.routing_key)
  return routing_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void BasicProperties::set_allocated_routing_key(std::string* routing_key) {
  if (routing_key != nullptr) {
    
  } else {
    
  }
  routing_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), routing_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:mq.BasicProperties.routing_key)
}

// -------------------------------------------------------------------

// Message_Payload

// .mq.BasicProperties properties = 1;
inline bool Message_Payload::_internal_has_properties() const {
  return this != internal_default_instance() && properties_ != nullptr;
}
inline bool Message_Payload::has_properties() const {
  return _internal_has_properties();
}
inline void Message_Payload::clear_properties() {
  if (GetArena() == nullptr && properties_ != nullptr) {
    delete properties_;
  }
  properties_ = nullptr;
}
inline const ::mq::BasicProperties& Message_Payload::_internal_properties() const {
  const ::mq::BasicProperties* p = properties_;
  return p != nullptr ? *p : reinterpret_cast<const ::mq::BasicProperties&>(
      ::mq::_BasicProperties_default_instance_);
}
inline const ::mq::BasicProperties& Message_Payload::properties() const {
  // @@protoc_insertion_point(field_get:mq.Message.Payload.properties)
  return _internal_properties();
}
inline void Message_Payload::unsafe_arena_set_allocated_properties(
    ::mq::BasicProperties* properties) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(properties_);
  }
  properties_ = properties;
  if (properties) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mq.Message.Payload.properties)
}
inline ::mq::BasicProperties* Message_Payload::release_properties() {
  
  ::mq::BasicProperties* temp = properties_;
  properties_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::mq::BasicProperties* Message_Payload::unsafe_arena_release_properties() {
  // @@protoc_insertion_point(field_release:mq.Message.Payload.properties)
  
  ::mq::BasicProperties* temp = properties_;
  properties_ = nullptr;
  return temp;
}
inline ::mq::BasicProperties* Message_Payload::_internal_mutable_properties() {
  
  if (properties_ == nullptr) {
    auto* p = CreateMaybeMessage<::mq::BasicProperties>(GetArena());
    properties_ = p;
  }
  return properties_;
}
inline ::mq::BasicProperties* Message_Payload::mutable_properties() {
  // @@protoc_insertion_point(field_mutable:mq.Message.Payload.properties)
  return _internal_mutable_properties();
}
inline void Message_Payload::set_allocated_properties(::mq::BasicProperties* properties) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete properties_;
  }
  if (properties) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(properties);
    if (message_arena != submessage_arena) {
      properties = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, properties, submessage_arena);
    }
    
  } else {
    
  }
  properties_ = properties;
  // @@protoc_insertion_point(field_set_allocated:mq.Message.Payload.properties)
}

// string body = 2;
inline void Message_Payload::clear_body() {
  body_.ClearToEmpty();
}
inline const std::string& Message_Payload::body() const {
  // @@protoc_insertion_point(field_get:mq.Message.Payload.body)
  return _internal_body();
}
inline void Message_Payload::set_body(const std::string& value) {
  _internal_set_body(value);
  // @@protoc_insertion_point(field_set:mq.Message.Payload.body)
}
inline std::string* Message_Payload::mutable_body() {
  // @@protoc_insertion_point(field_mutable:mq.Message.Payload.body)
  return _internal_mutable_body();
}
inline const std::string& Message_Payload::_internal_body() const {
  return body_.Get();
}
inline void Message_Payload::_internal_set_body(const std::string& value) {
  
  body_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Message_Payload::set_body(std::string&& value) {
  
  body_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:mq.Message.Payload.body)
}
inline void Message_Payload::set_body(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  body_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:mq.Message.Payload.body)
}
inline void Message_Payload::set_body(const char* value,
    size_t size) {
  
  body_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:mq.Message.Payload.body)
}
inline std::string* Message_Payload::_internal_mutable_body() {
  
  return body_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Message_Payload::release_body() {
  // @@protoc_insertion_point(field_release:mq.Message.Payload.body)
  return body_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Message_Payload::set_allocated_body(std::string* body) {
  if (body != nullptr) {
    
  } else {
    
  }
  body_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), body,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:mq.Message.Payload.body)
}

// string vaild = 3;
inline void Message_Payload::clear_vaild() {
  vaild_.ClearToEmpty();
}
inline const std::string& Message_Payload::vaild() const {
  // @@protoc_insertion_point(field_get:mq.Message.Payload.vaild)
  return _internal_vaild();
}
inline void Message_Payload::set_vaild(const std::string& value) {
  _internal_set_vaild(value);
  // @@protoc_insertion_point(field_set:mq.Message.Payload.vaild)
}
inline std::string* Message_Payload::mutable_vaild() {
  // @@protoc_insertion_point(field_mutable:mq.Message.Payload.vaild)
  return _internal_mutable_vaild();
}
inline const std::string& Message_Payload::_internal_vaild() const {
  return vaild_.Get();
}
inline void Message_Payload::_internal_set_vaild(const std::string& value) {
  
  vaild_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Message_Payload::set_vaild(std::string&& value) {
  
  vaild_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:mq.Message.Payload.vaild)
}
inline void Message_Payload::set_vaild(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  vaild_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:mq.Message.Payload.vaild)
}
inline void Message_Payload::set_vaild(const char* value,
    size_t size) {
  
  vaild_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:mq.Message.Payload.vaild)
}
inline std::string* Message_Payload::_internal_mutable_vaild() {
  
  return vaild_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Message_Payload::release_vaild() {
  // @@protoc_insertion_point(field_release:mq.Message.Payload.vaild)
  return vaild_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Message_Payload::set_allocated_vaild(std::string* vaild) {
  if (vaild != nullptr) {
    
  } else {
    
  }
  vaild_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), vaild,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:mq.Message.Payload.vaild)
}

// -------------------------------------------------------------------

// Message

// .mq.Message.Payload payload = 1;
inline bool Message::_internal_has_payload() const {
  return this != internal_default_instance() && payload_ != nullptr;
}
inline bool Message::has_payload() const {
  return _internal_has_payload();
}
inline void Message::clear_payload() {
  if (GetArena() == nullptr && payload_ != nullptr) {
    delete payload_;
  }
  payload_ = nullptr;
}
inline const ::mq::Message_Payload& Message::_internal_payload() const {
  const ::mq::Message_Payload* p = payload_;
  return p != nullptr ? *p : reinterpret_cast<const ::mq::Message_Payload&>(
      ::mq::_Message_Payload_default_instance_);
}
inline const ::mq::Message_Payload& Message::payload() const {
  // @@protoc_insertion_point(field_get:mq.Message.payload)
  return _internal_payload();
}
inline void Message::unsafe_arena_set_allocated_payload(
    ::mq::Message_Payload* payload) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(payload_);
  }
  payload_ = payload;
  if (payload) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mq.Message.payload)
}
inline ::mq::Message_Payload* Message::release_payload() {
  
  ::mq::Message_Payload* temp = payload_;
  payload_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::mq::Message_Payload* Message::unsafe_arena_release_payload() {
  // @@protoc_insertion_point(field_release:mq.Message.payload)
  
  ::mq::Message_Payload* temp = payload_;
  payload_ = nullptr;
  return temp;
}
inline ::mq::Message_Payload* Message::_internal_mutable_payload() {
  
  if (payload_ == nullptr) {
    auto* p = CreateMaybeMessage<::mq::Message_Payload>(GetArena());
    payload_ = p;
  }
  return payload_;
}
inline ::mq::Message_Payload* Message::mutable_payload() {
  // @@protoc_insertion_point(field_mutable:mq.Message.payload)
  return _internal_mutable_payload();
}
inline void Message::set_allocated_payload(::mq::Message_Payload* payload) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete payload_;
  }
  if (payload) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(payload);
    if (message_arena != submessage_arena) {
      payload = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, payload, submessage_arena);
    }
    
  } else {
    
  }
  payload_ = payload;
  // @@protoc_insertion_point(field_set_allocated:mq.Message.payload)
}

// uint32 offset = 2;
inline void Message::clear_offset() {
  offset_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::_internal_offset() const {
  return offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::offset() const {
  // @@protoc_insertion_point(field_get:mq.Message.offset)
  return _internal_offset();
}
inline void Message::_internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  offset_ = value;
}
inline void Message::set_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:mq.Message.offset)
}

// uint32 length = 3;
inline void Message::clear_length() {
  length_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::_internal_length() const {
  return length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Message::length() const {
  // @@protoc_insertion_point(field_get:mq.Message.length)
  return _internal_length();
}
inline void Message::_internal_set_length(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  length_ = value;
}
inline void Message::set_length(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:mq.Message.length)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mq

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::mq::ExchangeType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mq::ExchangeType>() {
  return ::mq::ExchangeType_descriptor();
}
template <> struct is_proto_enum< ::mq::DeliveryMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mq::DeliveryMode>() {
  return ::mq::DeliveryMode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
